apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notiflex-api
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: notiflex
spec:
  project: default
  source:
    repoURL: https://github.com/pyy0715/notiflex-platform.git
    targetRevision: main
    path: k8s/api
  destination:
    server: https://kubernetes.default.svc
    namespace: notiflex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
